ALTER TABLE quests INSERT COLUMN `ReqKillPlayer` int(10) UNSIGNED NOT NULL DEFAULT 0 AFTER `ReqItemCount4`;
ALTER TABLE quests INSERT COLUMN `RewBonusHonor` int(10) UNSIGNED NOT NULL DEFAULT 0 AFTER `RewMoney`;
ALTER TABLE quests INSERT COLUMN `RewTalentPoints` int(10) UNSIGNED NOT NULL DEFAULT 0 AFTER `RewSpell`;